AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam_backend

  Sample SAM Template for sam_backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    # maybe increase the timeout value...
    Timeout: 10

Resources:
  LogbookFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: logbook_filler/
      Handler: app.lambda_handler
      Runtime: python3.7
      # change event to cloudwatch event
      Events:
        TriggerEvent:
          Type: Schedule
          Properties:
            Schedule: rate(24 hours)

  CredentialsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: logbook-table
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "whatever"
    Value: "whatever"
